apiVersion: v1
kind: Secret
metadata:
  name: gloco-secrets
type: Opaque
data:
  APP_KEY: "YmFzZTY0OkhUV1VBWkxJTnJkOWVVWTF3VzlDSXljd1BkeXE5cDhjaXRONGczK0JuOHM9"
  DB_DATABASE: "Z2xvY28x"  # Base64 encoded
  DB_USERNAME: "Z2xvY29fdXNlcl9kYg=="  # Base64 encoded
  DB_PASSWORD: "UHIwZDdjdEQ0dDRCczMt"  # Base64 encoded
  MARIADB_ROOT_PASSWORD: "UjBvN1A0c3pXMGQt"  # Base64-encoded root password